waypoints:
  - point:
    - 0
    - 0
    - 0
    - 0
  - point:
    - -3
    - 0
    - 2.5
    - 0
    - 0
  - point:
    - -3.0
    - 4.5
    - 3.5
    - 0
  - point:
    - 3
    - 4
    - 2
    - 0
  - point:
    - 3
    - -4
    - 2
    - 0
  - point:
    - 0
    - 0
    - 0
    - 0